---
language: python
python: 2.7
sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

matrix:
  fast_finish: true

env:
  - TEST_RUN="./tests/test-docker-compose.sh"
  - TEST_RUN="./tests/test-kubernetes.sh"

before_install:
  - pip install yamllint

install:
  - "./scripts/install.sh"
  - "./scripts/bx_auth.sh"

before_script:
  - "./tests/test-shellcheck.sh"
  - "./tests/test-yamllint.sh"

script: "$TEST_RUN"
