postgresql:
  restart: always
  image: registry.ng.bluemix.net/${NAMESPACE}/gitlab-postgres:latest
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - postgresql:/var/lib/postgresql:rw
gitlab:
  restart: always
  image: registry.ng.bluemix.net/${NAMESPACE}/gitlab:latest
  links:
    - redis:redis
    - postgresql:postgresql
  ports:
    - "80:80"
    - "22:22"
  environment:
    - GITLAB_HOST=my.gitlab-server
  volumes:
    - gitlab:/home/git/data:rw
redis:
  restart: always
  image: registry.ng.bluemix.net/${NAMESPACE}/redis:latest
  volumes:
    - redis:/var/lib/redis:rw
