apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  ports:
    - port: 80
      nodePort: 30080
      name: gitlab
    - port: 22
      nodePort: 30022
      name: gitlab-ssh
  selector:
    app: gitlab
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-claim
  labels:
    app: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: frontend
    spec:
      containers:
      - image: docker.io/tomcli/gitlab:latest
        name: gitlab
        env:
        - name: GITLAB_HOST
          #your gitlab deployment name
          value: gitlab
        - name: DB_HOST
          #your postgreSQL deployment name
          value: postgresql
        - name: REDIS_HOST
          #your redis deployment name
          value: redis
        ports:
        - containerPort: 80
          name: gitlab
        volumeMounts:
        - name: gitlab
          mountPath: /home/git/data:rw
      volumes:
      - name: gitlab
        persistentVolumeClaim:
          claimName: gitlab-claim
